name: Cypress

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: nextcloud-vue

jobs:
  jest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run x copies of the current job in parallel
        containers: [1, 2]
        node-version: ['12.x']

    name: Runner ${{ matrix.containers }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
